# Generated by Django 6.0 on 2025-12-30 13:53

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employeeId', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('personalEmail', models.EmailField(max_length=254, unique=True)),
                ('collegeEmail', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(max_length=255)),
                ('btech', models.CharField(blank=True, max_length=255, null=True)),
                ('mtech', models.CharField(blank=True, max_length=255, null=True)),
                ('phd', models.CharField(blank=True, max_length=255, null=True)),
                ('office', models.CharField(max_length=255)),
                ('officeHours', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('aadhar', models.CharField(max_length=12, unique=True)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('phoneCode', models.IntegerField()),
                ('registrationNumber', models.IntegerField(unique=True)),
                ('rollNumber', models.IntegerField(unique=True)),
                ('passPort', models.CharField(default='Not Available', max_length=255)),
                ('emergencyContact', models.CharField(max_length=20)),
                ('personalEmail', models.EmailField(max_length=254, unique=True)),
                ('collegeEmail', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateTimeField()),
                ('address', models.TextField()),
                ('program', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('bloodGroup', models.CharField(max_length=10)),
                ('dayScholar', models.BooleanField()),
                ('fatherName', models.CharField(max_length=255)),
                ('fatherOccupation', models.CharField(blank=True, max_length=255, null=True)),
                ('fatherAadhar', models.CharField(blank=True, max_length=12, null=True)),
                ('fatherNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('motherName', models.CharField(max_length=255)),
                ('motherOccupation', models.CharField(blank=True, max_length=255, null=True)),
                ('motherAadhar', models.CharField(blank=True, max_length=12, null=True)),
                ('motherNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('community', models.CharField(choices=[('General', 'General'), ('OBC', 'Obc'), ('SC', 'Sc'), ('ST', 'St'), ('EWS', 'Ews')], max_length=10)),
                ('xMarks', models.IntegerField()),
                ('xiiMarks', models.IntegerField()),
                ('jeeMains', models.IntegerField()),
                ('jeeAdvanced', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PURSUING', 'Pursuing'), ('PASSEDOUT', 'Passedout')], default='PURSUING', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subjectName', models.CharField(max_length=255)),
                ('subjectCode', models.CharField(max_length=50, unique=True)),
                ('credits', models.IntegerField(default=3)),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('HOD', 'Hod'), ('ADMIN', 'Admin')], max_length=20)),
                ('profilePicture', models.URLField(blank=True, null=True)),
                ('accountStatus', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('comments', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(db_column='facultyId', on_delete=django.db.models.deletion.CASCADE, related_name='mentorships', to='core.faculty')),
                ('student', models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, related_name='mentorships', to='core.student')),
            ],
            options={
                'db_table': 'mentorships',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('facultyReview', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('YET_TO_DONE', 'Yet To Done'), ('COMPLETED', 'Completed'), ('REQUESTED', 'Requested')], default='UPCOMING', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('mentorship', models.ForeignKey(blank=True, db_column='mentorshipId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='core.mentorship')),
            ],
            options={
                'db_table': 'meetings',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('sgpa', models.FloatField()),
                ('cgpa', models.FloatField()),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='core.student')),
            ],
            options={
                'db_table': 'semesters',
                'unique_together': {('student', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('technologies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_mentored', to='core.faculty')),
                ('students', models.ManyToManyField(related_name='projects', to='core.student')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='PersonalProblem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stress', models.BooleanField(blank=True, null=True)),
                ('anger', models.BooleanField(blank=True, null=True)),
                ('examinationAnxiety', models.BooleanField(blank=True, null=True)),
                ('timeManagementProblem', models.BooleanField(blank=True, null=True)),
                ('procrastination', models.BooleanField(blank=True, null=True)),
                ('worriesAboutFuture', models.BooleanField(blank=True, null=True)),
                ('fearOfPublicSpeaking', models.BooleanField(blank=True, null=True)),
                ('student', models.OneToOneField(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, related_name='personalProblem', to='core.student')),
            ],
            options={
                'db_table': 'personal_problems',
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('organisation', models.CharField(max_length=255)),
                ('stipend', models.IntegerField()),
                ('duration', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('students', models.ManyToManyField(related_name='internships', to='core.student')),
            ],
            options={
                'db_table': 'internships',
            },
        ),
        migrations.CreateModel(
            name='CoCurricular',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sem', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('eventDetails', models.TextField()),
                ('participationDetails', models.TextField()),
                ('awards', models.CharField(max_length=255)),
                ('students', models.ManyToManyField(related_name='co_curriculars', to='core.student')),
            ],
            options={
                'db_table': 'co_curriculars',
            },
        ),
        migrations.CreateModel(
            name='CareerDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hobbies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('strengths', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('areasToImprove', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('core', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('it', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('higherEducation', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('startup', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('familyBusiness', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('otherInterests', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('student', models.OneToOneField(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, related_name='careerDetails', to='core.student')),
            ],
            options={
                'db_table': 'career_details',
            },
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=5)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='core.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='core.subject')),
            ],
            options={
                'db_table': 'student_subjects',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='student', to='core.user'),
        ),
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=255)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('faculty', models.OneToOneField(db_column='facultyId', on_delete=django.db.models.deletion.CASCADE, related_name='as_hod', to='core.faculty')),
                ('user', models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='hod', to='core.user')),
            ],
            options={
                'db_table': 'hods',
            },
        ),
        migrations.AddField(
            model_name='faculty',
            name='user',
            field=models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='core.user'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employeeId', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('personalEmail', models.EmailField(max_length=254, unique=True)),
                ('collegeEmail', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(max_length=255)),
                ('office', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='core.user')),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('INTERNSHIP', 'Internship'), ('PROJECT', 'Project'), ('PERFORMANCE', 'Performance'), ('CO_CURRICULAR', 'Co Curricular')], max_length=50)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, db_column='assignedToId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='core.faculty')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('student', models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.student')),
            ],
            options={
                'db_table': 'requests',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='requests_content_f25721_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mentorship',
            index=models.Index(fields=['faculty', 'is_active'], name='mentorships_faculty_7b41b3_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorship',
            index=models.Index(fields=['student', 'is_active'], name='mentorships_student_4494cf_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorship',
            index=models.Index(fields=['department'], name='mentorships_departm_4bc6b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mentorship',
            unique_together={('faculty', 'student', 'year', 'semester')},
        ),
        migrations.AddIndex(
            model_name='studentsubject',
            index=models.Index(fields=['student', 'semester'], name='student_sub_student_e78980_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentsubject',
            unique_together={('student', 'subject', 'semester')},
        ),
    ]
