# Generated by Django 6.0 on 2025-12-20 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(db_column='userId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='core.user'),
        ),
        migrations.AlterField(
            model_name='careerdetails',
            name='student',
            field=models.OneToOneField(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, related_name='careerDetails', to='core.student'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='user',
            field=models.OneToOneField(db_column='userId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='core.user'),
        ),
        migrations.AlterField(
            model_name='hod',
            name='faculty',
            field=models.OneToOneField(db_column='facultyId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_hod', to='core.faculty'),
        ),
        migrations.AlterField(
            model_name='hod',
            name='user',
            field=models.OneToOneField(db_column='userId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hod', to='core.user'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='mentor',
            field=models.ForeignKey(db_column='mentorId', on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='core.mentor'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='faculty',
            field=models.ForeignKey(db_column='facultyId', on_delete=django.db.models.deletion.CASCADE, related_name='mentorships', to='core.faculty'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='student',
            field=models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='core.student'),
        ),
        migrations.AlterField(
            model_name='personalproblem',
            name='student',
            field=models.OneToOneField(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, related_name='personalProblem', to='core.student'),
        ),
        migrations.AlterField(
            model_name='request',
            name='student',
            field=models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(db_column='userId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='core.user'),
        ),
        migrations.AlterModelTable(
            name='admin',
            table='admins',
        ),
        migrations.AlterModelTable(
            name='careerdetails',
            table='career_details',
        ),
        migrations.AlterModelTable(
            name='cocurricular',
            table='co_curriculars',
        ),
        migrations.AlterModelTable(
            name='faculty',
            table='faculty',
        ),
        migrations.AlterModelTable(
            name='hod',
            table='hods',
        ),
        migrations.AlterModelTable(
            name='internship',
            table='internships',
        ),
        migrations.AlterModelTable(
            name='meeting',
            table='meetings',
        ),
        migrations.AlterModelTable(
            name='mentor',
            table='mentors',
        ),
        migrations.AlterModelTable(
            name='personalproblem',
            table='personal_problems',
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
        migrations.AlterModelTable(
            name='request',
            table='requests',
        ),
        migrations.AlterModelTable(
            name='semester',
            table='semesters',
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='subjects',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
