# Generated by Django 6.0.1 on 2026-02-07 11:08

from django.db import migrations, models


def populate_hod_emails(apps, schema_editor):
    """Populate HOD email with a unique HOD-specific email"""
    HOD = apps.get_model('core', 'HOD')
    for idx, hod in enumerate(HOD.objects.all(), 1):
        # Use a unique HOD email (different from user.email)
        hod.email = f'hod{idx}@college.edu'
        hod.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        # Step 1: Add email field without unique constraint
        migrations.AddField(
            model_name='hod',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        # Step 2: Populate unique emails
        migrations.RunPython(populate_hod_emails, migrations.RunPython.noop),
        # Step 3: Add unique constraint
        migrations.AlterField(
            model_name='hod',
            name='email',
            field=models.EmailField(max_length=254, unique=True, default=''),
        ),
    ]
