# Generated by Django 6.0 on 2025-12-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='department',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Science & Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('BIO-TECH', 'Biotechnology'), ('MME', 'Metallurgical & Materials Engineering'), ('CHEM', 'Chemical Engineering')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('BIO-TECH', 'Biotechnology'), ('MME', 'Metallurgical & Materials Engineering'), ('CHEM', 'Chemical Engineering')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hod',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('BIO-TECH', 'Biotechnology'), ('MME', 'Metallurgical & Materials Engineering'), ('CHEM', 'Chemical Engineering')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('BIO-TECH', 'Biotechnology'), ('MME', 'Metallurgical & Materials Engineering'), ('CHEM', 'Chemical Engineering')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('BIO-TECH', 'Biotechnology'), ('MME', 'Metallurgical & Materials Engineering'), ('CHEM', 'Chemical Engineering')], max_length=20),
        ),
    ]
