# Generated by Django 6.0.1 on 2026-02-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hod_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
