# Generated by Django 6.0.1 on 2026-02-09 17:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_hod_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('BIO-TECH', 'Biotechnology'), ('MME', 'Metallurgical & Materials Engineering'), ('CHEM', 'Chemical Engineering')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('year', models.IntegerField(blank=True, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('UPCOMING', 'Upcoming'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('hod', models.ForeignKey(db_column='hodId', on_delete=django.db.models.deletion.CASCADE, related_name='meeting_windows', to='core.hod')),
            ],
            options={
                'db_table': 'meeting_windows',
            },
        ),
        migrations.CreateModel(
            name='MeetingReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('meetingDate', models.DateField()),
                ('meetingTime', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('isSubmitted', models.BooleanField(default=False)),
                ('submittedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(db_column='facultyId', on_delete=django.db.models.deletion.CASCADE, related_name='meeting_reports', to='core.faculty')),
                ('meeting_window', models.ForeignKey(db_column='meetingWindowId', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.meetingwindow')),
            ],
            options={
                'db_table': 'meeting_reports',
            },
        ),
        migrations.CreateModel(
            name='MeetingReportStudent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attended', models.BooleanField(default=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('meeting_report', models.ForeignKey(db_column='meetingReportId', on_delete=django.db.models.deletion.CASCADE, related_name='student_reports', to='core.meetingreport')),
                ('student', models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, related_name='meeting_report_reviews', to='core.student')),
            ],
            options={
                'db_table': 'meeting_report_students',
                'unique_together': {('meeting_report', 'student')},
            },
        ),
        migrations.AddIndex(
            model_name='meetingwindow',
            index=models.Index(fields=['department', 'status'], name='meeting_win_departm_f0cad9_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingwindow',
            index=models.Index(fields=['startDate', 'endDate'], name='meeting_win_startDa_98b0a0_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingreport',
            index=models.Index(fields=['faculty', 'isSubmitted'], name='meeting_rep_faculty_4a4a00_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingreport',
            index=models.Index(fields=['meeting_window', 'isSubmitted'], name='meeting_rep_meeting_f71ee9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='meetingreport',
            unique_together={('meeting_window', 'faculty', 'year', 'semester')},
        ),
    ]
