# Generated by Django 6.0 on 2025-12-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_year_to_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
