# Generated by Django 6.0 on 2025-12-31 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0005_add_faculty_dates_and_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_column='assignedToId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='core.faculty'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['student', 'status'], name='requests_student_85532d_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['assigned_to', 'status'], name='requests_assigne_b6c22c_idx'),
        ),
    ]
