# Generated by Django 6.0 on 2026-01-05 02:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_request_request_data_alter_request_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(db_column='receiverId', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='core.user')),
                ('sender', models.ForeignKey(db_column='senderId', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='core.user')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['-createdAt'],
                'indexes': [models.Index(fields=['sender', 'receiver'], name='messages_senderI_6bd406_idx'), models.Index(fields=['receiver', 'is_read'], name='messages_receive_9d3de1_idx')],
            },
        ),
    ]
