# Generated by Django 6.0 on 2026-01-05 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_message'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='messages_senderI_6bd406_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messages_receive_9d3de1_idx',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
