# Generated by Django 6.0 on 2026-01-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_message_messages_senderi_6bd406_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('INTERNSHIP', 'Internship'), ('PROJECT', 'Project'), ('PERFORMANCE', 'Performance'), ('CO_CURRICULAR', 'Co Curricular'), ('DELETE_INTERNSHIP', 'Delete Internship'), ('DELETE_PROJECT', 'Delete Project')], max_length=50),
        ),
    ]
