# Generated by Django 6.0 on 2026-01-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('INTERNSHIP', 'Internship'), ('PROJECT', 'Project'), ('PERFORMANCE', 'Performance'), ('CO_CURRICULAR', 'Co Curricular'), ('DELETE_INTERNSHIP', 'Delete Internship'), ('DELETE_PROJECT', 'Delete Project'), ('MEETING_REQUEST', 'Meeting Request')], max_length=50),
        ),
    ]
