# Generated by Django 6.0 on 2026-01-05 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_request_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocurricular',
            name='students',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='students',
        ),
        migrations.RemoveField(
            model_name='project',
            name='students',
        ),
        migrations.AddField(
            model_name='careerdetails',
            name='coreRank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetails',
            name='familyBusinessRank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetails',
            name='govtSectorRank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetails',
            name='higherEducationRank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetails',
            name='itRank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetails',
            name='startupRank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cocurricular',
            name='student',
            field=models.ForeignKey(blank=True, db_column='studentId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_curriculars', to='core.student'),
        ),
        migrations.AddField(
            model_name='internship',
            name='student',
            field=models.ForeignKey(blank=True, db_column='studentId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='core.student'),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='adjustmentProblem',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='conflicts',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='disappointmentWithCourse',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='disciplinaryProblemsInCollege',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='disturbedPeerRelationship',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='disturbedRelationshipWithParents',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='disturbedRelationshipWithTeachers',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='emotionalProblem',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='examPhobia',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='financialProblems',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='frustration',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='lackOfExpression',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='lowSelfEsteem',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='lowSelfMotivation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='migraineHeadache',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='moodSwings',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='negativeThoughts',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='poorCommandOfEnglish',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='poorConcentration',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='poorDecisivePower',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='poorMemoryProblem',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='relationshipProblems',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='stagePhobia',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='stammering',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='suicidalAttemptOrThought',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='tobaccoOrAlcoholUse',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='student',
            field=models.ForeignKey(blank=True, db_column='studentId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.student'),
        ),
        migrations.AlterField(
            model_name='cocurricular',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_mentored', to='core.faculty'),
        ),
    ]
