# Generated by Django 6.0 on 2026-01-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_adjustmentproblem_personalproblem_adjustment_problem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalproblem',
            name='additional_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='economic_issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='economic_issues_outcome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='economic_issues_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='emotional_issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='emotional_issues_outcome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='emotional_issues_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='health_issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='health_issues_outcome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='health_issues_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='psychological_issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='psychological_issues_outcome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='psychological_issues_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='teenage_issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='teenage_issues_outcome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalproblem',
            name='teenage_issues_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
