# Generated by Django 6.0 on 2026-01-07 15:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_personalproblem_additional_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingStudentReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(db_column='meetingId', on_delete=django.db.models.deletion.CASCADE, related_name='student_reviews', to='core.meeting')),
                ('student', models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, related_name='meeting_reviews', to='core.student')),
            ],
            options={
                'db_table': 'meeting_student_reviews',
                'unique_together': {('meeting', 'student')},
            },
        ),
    ]
