# Generated by Django 6.0 on 2026-01-07 16:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_meetingstudentreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, choices=[('CSE', 'Computer Science & Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('BIO-TECH', 'Biotechnology'), ('MME', 'Metallurgical & Materials Engineering'), ('CHEM', 'Chemical Engineering')], max_length=20, null=True)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('YET_TO_DONE', 'Yet To Done'), ('COMPLETED', 'Completed'), ('REQUESTED', 'Requested')], default='UPCOMING', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(db_column='facultyId', on_delete=django.db.models.deletion.CASCADE, related_name='group_meetings', to='core.faculty')),
            ],
            options={
                'db_table': 'group_meetings',
            },
        ),
        migrations.CreateModel(
            name='GroupMeetingStudent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review', models.TextField(blank=True, null=True)),
                ('attended', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('group_meeting', models.ForeignKey(db_column='groupMeetingId', on_delete=django.db.models.deletion.CASCADE, related_name='student_reviews', to='core.groupmeeting')),
                ('student', models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, related_name='group_meeting_reviews', to='core.student')),
            ],
            options={
                'db_table': 'group_meeting_students',
            },
        ),
        migrations.AddIndex(
            model_name='groupmeeting',
            index=models.Index(fields=['faculty', 'year', 'semester'], name='group_meeti_faculty_5ab2d8_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmeeting',
            index=models.Index(fields=['date', 'status'], name='group_meeti_date_9784ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmeetingstudent',
            unique_together={('group_meeting', 'student')},
        ),
    ]
