# Generated by Django 6.0 on 2026-01-13 08:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_group_meeting_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacklogHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_semester', models.IntegerField()),
                ('attempt_number', models.IntegerField(default=1)),
                ('attempt_type', models.CharField(choices=[('REGULAR', 'Regular Exam'), ('BACKLOG', 'Backlog Exam'), ('MAKEUP', 'Makeup Exam')], max_length=10)),
                ('semester_type', models.CharField(choices=[('ODD', 'Odd Semester (1, 3, 5, 7)'), ('EVEN', 'Even Semester (2, 4, 6, 8)')], max_length=10)),
                ('exam_year', models.IntegerField()),
                ('exam_month', models.CharField(max_length=20)),
                ('grade', models.CharField(choices=[('EX', 'Excellent (10)'), ('A', 'A Grade (9)'), ('B', 'B Grade (8)'), ('C', 'C Grade (7)'), ('D', 'D Grade (6)'), ('P', 'Pass (5)'), ('F', 'Fail (0)'), ('X', 'Absent (0)')], max_length=5)),
                ('grade_point', models.IntegerField(default=0)),
                ('is_cleared', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'backlog_history',
                'ordering': ['attempt_number'],
            },
        ),
        migrations.CreateModel(
            name='FacultySubjectHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.IntegerField()),
                ('semester_type', models.CharField(choices=[('ODD', 'Odd Semester (1, 3, 5, 7)'), ('EVEN', 'Even Semester (2, 4, 6, 8)')], max_length=10)),
                ('is_current', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'faculty_subject_history',
                'ordering': ['-academic_year', '-semester_type'],
            },
        ),
        migrations.CreateModel(
            name='YearTopper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('BIO-TECH', 'Biotechnology'), ('MME', 'Metallurgical & Materials Engineering'), ('CHEM', 'Chemical Engineering')], max_length=20)),
                ('academic_year', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('cgpa', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'year_toppers',
                'ordering': ['department', 'academic_year', 'rank'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='studentsubject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='semester',
            name='academic_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='earned_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semester',
            name='semester_type',
            field=models.CharField(blank=True, choices=[('ODD', 'Odd Semester (1, 3, 5, 7)'), ('EVEN', 'Even Semester (2, 4, 6, 8)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='total_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semester',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='attempt_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Exam'), ('BACKLOG', 'Backlog Exam'), ('MAKEUP', 'Makeup Exam')], default='REGULAR', max_length=10),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='exam_month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='exam_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='grade_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='passing_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='current_faculty',
            field=models.ManyToManyField(blank=True, related_name='current_subjects', to='core.faculty'),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Science & Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('BIO-TECH', 'Biotechnology'), ('MME', 'Metallurgical & Materials Engineering'), ('CHEM', 'Chemical Engineering')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='past_faculty',
            field=models.ManyToManyField(blank=True, related_name='past_subjects', to='core.faculty'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(blank=True, choices=[('BSC', 'Basic Science Core'), ('ESC', 'Engineering Science Core'), ('HSC', 'Humanities and Social Science Core'), ('PCC', 'Program Core Courses'), ('DEC', 'Departmental Elective Courses'), ('OPC', 'Open Elective Courses'), ('MSC', 'EAA: Games and Sports'), ('MOE', 'MOOCs'), ('PRC', 'Program Major Project/Skill Development/Foreign Languages')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='typical_semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='cgpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='semester',
            name='sgpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='studentsubject',
            name='grade',
            field=models.CharField(choices=[('EX', 'Excellent (10)'), ('A', 'A Grade (9)'), ('B', 'B Grade (8)'), ('C', 'C Grade (7)'), ('D', 'D Grade (6)'), ('P', 'Pass (5)'), ('F', 'Fail (0)'), ('X', 'Absent (0)')], max_length=5),
        ),
        migrations.AddIndex(
            model_name='studentsubject',
            index=models.Index(fields=['student', 'subject'], name='student_sub_student_19a012_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsubject',
            index=models.Index(fields=['attempt_type'], name='student_sub_attempt_bbb19c_idx'),
        ),
        migrations.AddField(
            model_name='backloghistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlog_history', to='core.student'),
        ),
        migrations.AddField(
            model_name='backloghistory',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlog_attempts', to='core.subject'),
        ),
        migrations.AddField(
            model_name='facultysubjecthistory',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_history', to='core.faculty'),
        ),
        migrations.AddField(
            model_name='facultysubjecthistory',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_history', to='core.subject'),
        ),
        migrations.AddField(
            model_name='yeartopper',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topper_ranks', to='core.student'),
        ),
        migrations.AddIndex(
            model_name='backloghistory',
            index=models.Index(fields=['student', 'subject'], name='backlog_his_student_518bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='backloghistory',
            index=models.Index(fields=['is_cleared'], name='backlog_his_is_clea_419538_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='facultysubjecthistory',
            unique_together={('faculty', 'subject', 'academic_year', 'semester_type')},
        ),
        migrations.AlterUniqueTogether(
            name='yeartopper',
            unique_together={('department', 'academic_year', 'rank')},
        ),
    ]
