# Generated by Django 6.0 on 2026-01-13 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_backloghistory_facultysubjecthistory_yeartopper_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='earned_credits',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='current_faculty',
        ),
        migrations.AddField(
            model_name='subject',
            name='current_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_subjects', to='core.faculty'),
        ),
    ]
